=== arjun27pm/CAT1/company.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Studio 2021 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="emp_id" type="xs:string"></xs:element>
                            <xs:element name="emp_name" type="xs:string"></xs:element>
                            <xs:element name="emp_age" type="xs:integer"></xs:element>
                            <xs:element name="emp_sal" type="xs:integer"></xs:element>
                            <xs:element name="emp_email" type="xs:string"></xs:element>
                            <xs:element name="emp_mob" type="xs:string"></xs:element>
                            <xs:element name="emp_designation" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="emp_id">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="emp_age">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="21"/>
                <xs:maxInclusive value="65"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="salary">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="50000"/>
                <xs:maxInclusive value="200000"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>


</xs:schema>

=== arjun27pm/CAT1/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="company2.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="company.xsd">
    <employee>
        <emp_id>01</emp_id>
            <emp_name>benzema</emp_name>
            <emp_age>24</emp_age>
            <emp_sal>95000</emp_sal>
            <emp_email>haaland@gmail.com</emp_email>
            <emp_mob>022-333-44-2</emp_mob>
            <emp_designation>associate project manager</emp_designation>
    </employee>
    <employee>
        <emp_id>02</emp_id>
        <emp_name>vini jr</emp_name>
        <emp_age>22</emp_age>
        <emp_sal>155000</emp_sal>
        <emp_email>vjr@gmail.com</emp_email>
        <emp_mob>011-433-743</emp_mob>
        <emp_designation> project member</emp_designation>
    </employee>
    <employee>
        <emp_id>03</emp_id>
        <emp_name>f.valverde</emp_name>
        <emp_age>23</emp_age>
        <emp_sal>85000</emp_sal>
        <emp_email>fede@gmail.com</emp_email>
        <emp_mob>092-553-102</emp_mob>
        <emp_designation>developer</emp_designation>
    </employee>
    <employee>
        <emp_id>04</emp_id>
        <emp_name>Rodrigo</emp_name>
        <emp_age>25</emp_age>
        <emp_sal>90000</emp_sal>
        <emp_email>rsantos@gmail.com</emp_email>
        <emp_mob>099-7654-22</emp_mob>
        <emp_designation>team leader</emp_designation>
    </employee>
    <employee>
        <emp_id>05</emp_id>
        <emp_name>kroos</emp_name>
        <emp_age>30</emp_age>
        <emp_sal>65000</emp_sal>
        <emp_email>toni@gmail.com</emp_email>
        <emp_mob>011-7787-10</emp_mob>
        <emp_designation>team leader</emp_designation>
    </employee>
    <employee>
        <emp_id>06</emp_id>
        <emp_name>casemiro</emp_name>
        <emp_age>50</emp_age>
        <emp_sal>75000</emp_sal>
        <emp_email>case14@gmail.com</emp_email>
        <emp_mob>066-4004-7</emp_mob>
        <emp_designation>developer</emp_designation>
    </employee>
    <employee>
        <emp_id>07</emp_id>
        <emp_name>courtois</emp_name>
        <emp_age>47</emp_age>
        <emp_sal>50000</emp_sal>
        <emp_email>tibetc@gmail.com</emp_email>
        <emp_mob>032-369-11-2</emp_mob>
        <emp_designation>developer</emp_designation>
    </employee>
    
</company>
